import { supabase } from './supabase';
import type { Recruitment, Application, MockQuestion } from '../types';

const STORAGE_KEY_JOBS = 'codeprint_recruitments';
const STORAGE_KEY_APPS = 'codeprint_applications';

const SAMPLE_RECRUITMENTS: Recruitment[] = [
  {
    id: 'rec-1',
    company_id: 'comp-demo-1',
    title: 'Senior Frontend & AI Engineer',
    description: 'We are seeking an exceptional frontend architect with strong TypeScript and LLM application development skills to spearhead our next-generation product suite.',
    role_type: 'Full-time Hybrid',
    status: 'open',
    skills: ['React', 'TypeScript', 'Node.js', 'OpenAI', 'Tailwind CSS'],
    academic_criteria: 'B.Tech / B.E in Computer Science or Equivalent Enterprise Experience',
    cgpa_cutoff: 7.5,
    eligible_branches: ['Computer Science', 'Information Technology', 'AI & Machine Learning'],
    deadline: '2026-08-30',
    criteria_weightage: { skills: 60, cgpa: 15, projects: 25 },
    posting_type: 'Direct AI Track',
    created_at: new Date().toISOString(),
    profiles: {
      full_name: 'Google DeepMind Tech Team',
      company_name: 'Google DeepMind AI',
      id: 'comp-demo-1'
    },
    mock_test: {
      enabled: true,
      title: 'Advanced React & AI Engineering Qualification Assessment',
      duration_minutes: 15,
      passing_percentage: 70,
      questions: [
        {
          id: 'q1',
          question: 'In React 19, how do concurrency features such as useTransition optimize responsiveness during heavy LLM data processing?',
          options: [
            'By synchronously blocking browser rendering until state resolves',
            'By marking non-urgent state updates as interruptible transitions, preserving UI smoothness',
            'By compiling components directly to assembly code in Worker threads',
            'By bypassing the virtual DOM hierarchy entirely'
          ],
          correct_index: 1,
          explanation: 'useTransition marks state updates as interruptible, allowing user interactions to preempt long-running renders.'
        },
        {
          id: 'q2',
          question: 'When implementing conversational AI pipelines, what is the primary benefit of stream tokenization over standard REST payload batching?',
          options: [
            'Decreased database query storage requirements',
            'Drastically reduced Time-to-First-Token (TTFT), significantly improving user perceived latency',
            'Eliminates the need for API authentication headers',
            'Ensures deterministic output generation without temperature controls'
          ],
          correct_index: 1,
          explanation: 'Streaming tokens as they are generated by the LLM minimizes Time-to-First-Token latency.'
        },
        {
          id: 'q3',
          question: 'What is the most robust strategy to prevent memory leaks when managing complex WebSocket connections inside React functional components?',
          options: [
            'Storing the WebSocket instance in global window namespace',
            'Instantiating inside render body without dependency arrays',
            'Using a useRef to maintain reference and cleaning up connections inside useEffect return function',
            'Relying solely on browser automatic garbage collection upon tab reload'
          ],
          correct_index: 2,
          explanation: 'useEffect cleanups paired with useRef ensure WebSocket handles are closed when components unmount or re-render.'
        }
      ]
    }
  },
  {
    id: 'rec-2',
    company_id: 'comp-demo-2',
    title: 'Distributed Systems & Cloud Architect',
    description: 'Design and deploy ultra-high throughput distributed database storage engines and Kubernetes orchestration clusters.',
    role_type: 'Full-time Remote',
    status: 'open',
    skills: ['Golang', 'Rust', 'Kubernetes', 'Docker', 'PostgreSQL'],
    academic_criteria: 'Open to All Engineering Disciplines with Verified High Talent Scores',
    cgpa_cutoff: 7.0,
    eligible_branches: ['Computer Science', 'Electrical Engineering', 'Mathematics'],
    deadline: '2026-09-15',
    criteria_weightage: { skills: 50, cgpa: 20, projects: 30 },
    posting_type: 'Open Enterprise Application',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    profiles: {
      full_name: 'Stripe Cloud Infrastructure',
      company_name: 'Stripe Infrastructure',
      id: 'comp-demo-2'
    },
    mock_test: {
      enabled: false,
      title: 'General Systems Evaluation',
      duration_minutes: 20,
      passing_percentage: 60,
      questions: []
    }
  }
];

export const recruitmentService = {
  getRecruitments: async (companyId?: string): Promise<Recruitment[]> => {
    let stored = localStorage.getItem(STORAGE_KEY_JOBS);
    let localJobs: Recruitment[] = stored ? JSON.parse(stored) : [];
    
    if (localJobs.length === 0) {
      localJobs = [...SAMPLE_RECRUITMENTS];
      localStorage.setItem(STORAGE_KEY_JOBS, JSON.stringify(localJobs));
    }

    try {
      let query = supabase
        .from('recruitments')
        .select('*, profiles:company_id(id, full_name, company_name)')
        .order('created_at', { ascending: false });

      if (companyId) {
        query = query.eq('company_id', companyId);
      }

      const { data, error } = await query;
      if (!error && data && data.length > 0) {
        const merged = [...data as Recruitment[]];
        localJobs.forEach(localJob => {
          if (!merged.some(m => m.id === localJob.id)) {
            if (!companyId || localJob.company_id === companyId) {
              merged.push(localJob);
            }
          }
        });
        return companyId ? merged.filter(m => m.company_id === companyId) : merged;
      }
    } catch (e) {
      console.warn('Supabase fetch failed, relying on offline persistent store:', e);
    }

    if (companyId) {
      return localJobs.filter(j => j.company_id === companyId);
    }
    return localJobs;
  },

  createRecruitment: async (job: Omit<Recruitment, 'id' | 'created_at' | 'applicant_count'>): Promise<Recruitment> => {
    const newJob: Recruitment = {
      ...job,
      id: `rec-${Date.now()}-${Math.random().toString(36).substr(2, 4)}`,
      created_at: new Date().toISOString(),
      applicant_count: 0
    };

    const stored = localStorage.getItem(STORAGE_KEY_JOBS);
    const localJobs: Recruitment[] = stored ? JSON.parse(stored) : [...SAMPLE_RECRUITMENTS];
    localJobs.unshift(newJob);
    localStorage.setItem(STORAGE_KEY_JOBS, JSON.stringify(localJobs));

    try {
      await supabase.from('recruitments').insert({
        id: newJob.id,
        company_id: newJob.company_id,
        title: newJob.title,
        description: newJob.description,
        role_type: newJob.role_type,
        status: newJob.status,
        skills: newJob.skills,
        academic_criteria: newJob.academic_criteria,
        cgpa_cutoff: newJob.cgpa_cutoff,
        eligible_branches: newJob.eligible_branches,
        deadline: newJob.deadline,
        criteria_weightage: newJob.criteria_weightage,
        posting_type: newJob.posting_type,
        mock_test: newJob.mock_test,
        created_at: newJob.created_at
      });
    } catch (err) {
      console.warn('Could not save job to Supabase, persisted cleanly to local sync storage:', err);
    }

    return newJob;
  },

  updateRecruitment: async (jobId: string, updates: Partial<Recruitment>): Promise<void> => {
    const stored = localStorage.getItem(STORAGE_KEY_JOBS);
    let localJobs: Recruitment[] = stored ? JSON.parse(stored) : [...SAMPLE_RECRUITMENTS];
    const target = localJobs.find(j => j.id === jobId);
    if (target) {
      Object.assign(target, updates);
      localStorage.setItem(STORAGE_KEY_JOBS, JSON.stringify(localJobs));
    }
    try {
      await supabase.from('recruitments').update(updates).eq('id', jobId);
    } catch { /* offline fallback */ }
  },

  getApplications: async (filter?: { studentId?: string; recruitmentId?: string; companyId?: string }): Promise<Application[]> => {
    const stored = localStorage.getItem(STORAGE_KEY_APPS);
    let localApps: Application[] = stored ? JSON.parse(stored) : [];
    const storedJobs = localStorage.getItem(STORAGE_KEY_JOBS);
    const localJobs: Recruitment[] = storedJobs ? JSON.parse(storedJobs) : [...SAMPLE_RECRUITMENTS];

    const enrichApp = (app: any): Application => {
      const rec = app.recruitments || localJobs.find(j => j.id === app.recruitment_id);
      return {
        ...app,
        recruitments: rec,
        profiles: app.profiles || {
          id: app.student_id,
          full_name: app.profiles?.full_name || 'Candidate Profile',
          email: app.profiles?.email || 'applicant@codeprint.ai',
          talent_score: app.profiles?.talent_score || app.ai_match_score || 85,
          ai_profile_score: app.profiles?.ai_profile_score || 88
        }
      } as Application;
    };

    localApps = localApps.map(enrichApp);

    try {
      let query = supabase.from('applications').select('*, recruitments(*), profiles:student_id(*)').order('applied_at', { ascending: false });
      if (filter?.studentId) query = query.eq('student_id', filter.studentId);
      if (filter?.recruitmentId) query = query.eq('recruitment_id', filter.recruitmentId);

      const { data, error } = await query;
      if (!error && data) {
        const dbApps = (data as Application[]).map(enrichApp);
        localApps.forEach(la => {
          if (!dbApps.some(da => da.id === la.id)) dbApps.push(la);
        });
        return filterApplications(dbApps, filter, localJobs);
      }
    } catch (e) {
      console.warn('Offline application retrieval fallback:', e);
    }

    return filterApplications(localApps, filter, localJobs);
  },

  submitApplication: async (appData: Omit<Application, 'id' | 'applied_at'>): Promise<Application> => {
    const newApp: Application = {
      ...appData,
      id: `app-${Date.now()}-${Math.random().toString(36).substr(2, 4)}`,
      applied_at: new Date().toISOString()
    };

    const stored = localStorage.getItem(STORAGE_KEY_APPS);
    const localApps: Application[] = stored ? JSON.parse(stored) : [];
    const idx = localApps.findIndex(a => a.student_id === appData.student_id && a.recruitment_id === appData.recruitment_id);
    if (idx >= 0) {
      localApps[idx] = newApp;
    } else {
      localApps.unshift(newApp);
    }
    localStorage.setItem(STORAGE_KEY_APPS, JSON.stringify(localApps));

    try {
      await supabase.from('applications').upsert({
        id: newApp.id,
        recruitment_id: newApp.recruitment_id,
        student_id: newApp.student_id,
        status: newApp.status,
        ai_match_score: newApp.ai_match_score,
        assessment_score: newApp.assessment_score,
        assessment_passed: newApp.assessment_passed,
        fraud_risk_level: newApp.fraud_risk_level,
        fraud_analysis: newApp.fraud_analysis,
        applied_at: newApp.applied_at
      });
    } catch (e) {
      console.warn('Offline application creation fallback:', e);
    }

    return newApp;
  },

  updateApplicationStatus: async (appId: string, status: 'pending' | 'accepted' | 'rejected', notes?: string): Promise<void> => {
    const stored = localStorage.getItem(STORAGE_KEY_APPS);
    if (stored) {
      const apps: Application[] = JSON.parse(stored);
      const target = apps.find(a => a.id === appId);
      if (target) {
        target.status = status;
        if (notes !== undefined) target.recruiter_notes = notes;
        localStorage.setItem(STORAGE_KEY_APPS, JSON.stringify(apps));
      }
    }
    try {
      await supabase.from('applications').update({ status, recruiter_notes: notes }).eq('id', appId);
    } catch { /* offline fallback */ }
  },

  updateApplicationFields: async (appId: string, updates: Record<string, any>): Promise<void> => {
    const stored = localStorage.getItem(STORAGE_KEY_APPS);
    if (stored) {
      const apps: Application[] = JSON.parse(stored);
      const target = apps.find(a => a.id === appId);
      if (target) {
        Object.assign(target, updates);
        localStorage.setItem(STORAGE_KEY_APPS, JSON.stringify(apps));
      }
    }
    try {
      await supabase.from('applications').update(updates).eq('id', appId);
    } catch { /* offline fallback */ }
  },

  generateAiQuestions: (skills: string[]): MockQuestion[] => {
    const defaultQs: MockQuestion[] = [
      {
        id: `gen-${Math.random().toString(36).substr(2, 5)}`,
        question: `How would you architect a fault-tolerant caching pattern for microservices handling high concurrency in ${skills[0] || 'Modern Software Engine'}?`,
        options: [
          'Using synchronous disk file writes on every request read',
          'Implementing distributed Redis caching with Write-Through or LRU eviction policies and database fallbacks',
          'Reloading all static data on every single HTTPS incoming request',
          'Bypassing server memory entirely and storing data in user URL parameters'
        ],
        correct_index: 1,
        explanation: 'Distributed caching with LRU and fallback strategies ensures high read performance and fault tolerance.'
      },
      {
        id: `gen-${Math.random().toString(36).substr(2, 5)}`,
        question: `In production ${skills[0] || 'Enterprise'} deployments, what is the safest methodology to handle backwards-incompatible database migrations without downtime?`,
        options: [
          'Drop the table in production and recreate it with new indexes',
          'Perform a rolling zero-downtime multi-phase expand/contract (parallel write) schema pattern',
          'Shut down the web server for 2 hours during maintenance window',
          'Force client browsers to clear local storage and refresh sessions'
        ],
        correct_index: 1,
        explanation: 'The Expand/Contract multi-phase migration pattern allows existing code to read old schemas while new services write to updated schemas.'
      },
      {
        id: `gen-${Math.random().toString(36).substr(2, 5)}`,
        question: 'When evaluating complex computational workflows, how does asynchronous message queuing (e.g., Kafka, RabbitMQ) enhance API resilience?',
        options: [
          'By encrypting TLS certificates over HTTP/2 traffic',
          'By decoupling ingestion rate from background workers, buffering sudden traffic bursts and preventing server exhaustion',
          'By compressing JSON payloads into binary XML blobs',
          'By removing the necessity of database transaction isolation'
        ],
        correct_index: 1,
        explanation: 'Message queues buffer request spikes and decouple ingest from computationally expensive worker processing.'
      }
    ];
    return defaultQs;
  }
};

function filterApplications(apps: Application[], filter?: { studentId?: string; recruitmentId?: string; companyId?: string }, jobs?: Recruitment[]): Application[] {
  if (!filter) return apps;
  return apps.filter(a => {
    if (filter.studentId && a.student_id !== filter.studentId) return false;
    if (filter.recruitmentId && a.recruitment_id !== filter.recruitmentId) return false;
    if (filter.companyId) {
      const compId = a.recruitments?.company_id || jobs?.find(j => j.id === a.recruitment_id)?.company_id;
      if (compId && compId !== filter.companyId) return false;
    }
    return true;
  });
}
